development:
  adapter: postgresql
  encoding: utf8
  database: kzs_development
  username:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: kzs_test
  username:
  host: localhost
#selectel
# production:
#   adapter: postgresql
#   host: localhost
#   encoding: utf8
#   database: kzs-staging
#   pool: 5
#   username: user
#   password: ks86ybdl!

#mercury
production:
  adapter: postgresql
  encoding: utf8
  database: kzs_development
  username:
  host: localhost

# mars
# production:
#   adapter: postgresql
#   host: localhost
#   encoding: utf8
#   database: postgres
#   pool: 5
#   username: sake
#   password: ARprmSbqIl1eFphH
