# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: babrovka.ru
  encoding: utf8
  database: kzs-staging
  pool: 5
  username: user
  password: ks86ybdl!

production:
  adapter: postgresql
  host: babrovka.ru
  encoding: utf8
  database: kzs-staging
  pool: 5
  username: user
  password: ks86ybdl!



# production:
#   adapter: postgresql
#   host: localhost
#   encoding: utf8
#   database: postgres
#   pool: 5
#   username: sake
#   password: ARprmSbqIl1eFphH
