# CONNECT TO STAGING DB
#development:
#  adapter: postgresql
#  host: babrovka.ru
#  encoding: utf8
#  database: kzs-staging
#  pool: 5
#  username: user
#  password: ks86ybdl!

development:
  adapter: postgresql
  encoding: utf8
  database: kzs_development
  username:
  host: localhost

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: kzs-staging
  pool: 5
  username: user
  password: ks86ybdl!



# production:
#   adapter: postgresql
#   host: localhost
#   encoding: utf8
#   database: postgres
#   pool: 5
#   username: sake
#   password: ARprmSbqIl1eFphH
